version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "${HTTP_HOST_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${DB_JDBC_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      # Super-User: by default POSTGRES_USER="postgres"
      - "POSTGRES_DB=${POSTGRES_DB}"
      #      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5



